CREATE TABLE person (
	id_person NUMBER(8) CONSTRAINT PK_person PRIMARY KEY,
	mail VARCHAR2(200) not null,
	mdp VARCHAR2(10) not null
);

CREATE TABLE cle (
	id_cle NUMBER(8) CONSTRAINT PK_cle PRIMARY KEY,
	cle VARCHAR2(60) not null UNIQUE
);

CREATE SEQUENCE seq_person
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NOMAXVALUE
	NOCYCLE
	CACHE 20;
	
CREATE SEQUENCE seq_cle
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
CACHE 20;

