CREATE TABLE person (
	id NUMBER(8) CONSTRAINT PK_person PRIMARY KEY,
	mail VARCHAR2(200) not null,
	mdp VARCHAR2(10) not null
);

CREATE SEQUENCE seq_person
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NOMAXVALUE
	NOCYCLE
	CACHE 20;

